export const DEFAULT_FRAGMENT_SUFFIXES = ['Fragment'];
export const DEFAULT_QUERY_PREFIXES = ['GET'];
export const DEFAULT_MUTATION_PREFIXES = [
  'CREATE',
  'UPDATE',
  'DELETE',
  'BULK_CREATE',
  'BULK_UPDATE',
  'BULK_DELETE',
];
